name: C/C++ CI Meson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential meson libacl1-dev libattr1-dev libgtkmm-3.0-dev libnautilus-extension-dev gettext
    - name: Setup meson
      run: |
        mkdir build
        cd build && meson .. 
    - name: Build
      run: cd build && meson compile
